version: "3"

services:
  gocd:
    image: gocd/gocd-server:v17.8.0
    ports:
      - "8153:8153"
    environment:
      - GO_SERVER_SYSTEM_PROPERTIES="-DpluginLocationMonitor.sleepTimeInSecs=3"
    volumes:
      - ./go/data:/godata
      - ./go/home:/home/go
    links:
      - node

  node:
    build: ./server
    ports:
      - "3000:3000"
