version: "3"

services:
  gocd:
    image: gocd/gocd-server:v17.8.0
    ports:
      - "8153:8153"
    volumes:
      - ./go/data:/godata
      - ./go/home:/home/go

  node:
    image: node:alpine
    command: node index.js
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./server:/app
